// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef _VTOP_TOP_H_
#define _VTOP_TOP_H_  // guard

#include "verilated_heavy.h"
#include "Vtop__Dpi.h"

//==========

class Vtop__Syms;
class Vtop_VerilatedVcd;
class Vtop_ram__A14;


//----------

VL_MODULE(Vtop_top) {
  public:
    // CELLS
    Vtop_ram__A14* ram_i;
    
    // PORTS
    VL_IN8(clk_i,0,0);
    VL_IN8(rstn_i,0,0);
    VL_IN8(irq_i,0,0);
    VL_IN8(irq_id_i,4,0);
    VL_OUT8(irq_ack_o,0,0);
    VL_OUT8(irq_id_o,4,0);
    VL_IN8(irq_sec_i,0,0);
    VL_OUT8(sec_lvl_o,0,0);
    VL_IN8(debug_req_i,0,0);
    VL_OUT8(debug_gnt_o,0,0);
    VL_OUT8(debug_rvalid_o,0,0);
    VL_IN8(debug_we_i,0,0);
    VL_OUT8(debug_halted_o,0,0);
    VL_IN8(fetch_enable_i,0,0);
    VL_OUT8(core_busy_o,0,0);
    VL_IN16(debug_addr_i,14,0);
    VL_IN(debug_wdata_i,31,0);
    VL_OUT(debug_rdata_o,31,0);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __PVT__instr_req;
        CData/*0:0*/ __PVT__data_req;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__apu_master_gnt_i;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__apu_master_valid_i;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__apu_master_flags_i;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ext_perf_counters_i;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__is_hwlp_id;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__hwlp_dec_cnt_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__instr_valid_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__is_compressed_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__illegal_c_insn_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__clear_instr_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__pc_set;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__pc_mux_id;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__exc_pc_mux_id;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__exc_cause;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__trap_addr_mux;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__is_decoding;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__useincr_addr_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__data_misaligned;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__mult_multicycle;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__branch_in_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ctrl_busy;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__alu_en_ex;
        CData/*6:0*/ __PVT__riscv_core_i__DOT__alu_operator_ex;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__bmask_a_ex;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__bmask_b_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__imm_vec_ext_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__alu_vec_mode_ex;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__mult_operator_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__mult_en_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__mult_sel_subword_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__mult_signed_mode_ex;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__mult_imm_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__mult_dot_signed_ex;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__fpu_op_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__apu_en_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__apu_type_ex;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__apu_op_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__apu_lat_ex;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__apu_waddr_ex;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__regfile_waddr_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__regfile_we_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__regfile_we_wb;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__regfile_alu_waddr_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__regfile_alu_we_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__regfile_alu_we_fw;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_access_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__csr_op_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_access;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__csr_op;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__data_we_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__data_type_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__data_sign_ext_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__data_reg_offset_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__data_req_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__data_load_event_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__data_misaligned_ex;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__halt_if;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_ready;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_ready;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__lsu_ready_ex;
    };
    struct {
        CData/*0:0*/ __PVT__riscv_core_i__DOT__lsu_ready_wb;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__instr_req_int;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__m_irq_enable;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_irq_sec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_save_cause;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_save_if;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_save_id;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__csr_cause;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_restore_mret_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_restore_uret_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__csr_hwlp_regid;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__csr_hwlp_we;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__dbg_req;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__dbg_ack;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__dbg_stall;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__dbg_trap;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__dbg_csr_we;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__core_ctrl_firstfetch;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__core_busy_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__offset_fsm_cs;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__offset_fsm_ns;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__if_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__branch_req;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_ready;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__is_hwlp_id_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_is_hwlp;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__hwlp_branch;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__hwlp_dec_cnt;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__hwlp_dec_cnt_if;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__illegal_c_insn;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__hwloop_controller_i__DOT__pc_is_end_addr;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__busy_L0;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__CS;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__NS;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__do_fetch;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__do_hwlp;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__do_hwlp_int;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__use_last;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__save_rdata_last;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__use_hwlp;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__save_rdata_hwlp;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__hwlp_is_crossword;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__is_crossword;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__next_is_crossword;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__next_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__next_upper_compressed;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__is_hwlp_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__is_hwlp_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__fetch_valid;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__CS;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__NS;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__deassert_we;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__illegal_insn_dec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__ebrk_insn;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__mret_insn_dec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__uret_insn_dec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__ecall_insn_dec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__pipe_flush_dec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__rega_used_dec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regb_used_dec;
    };
    struct {
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regc_used_dec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__branch_taken_ex;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__jump_in_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__jr_stall;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__load_stall;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__instr_multicycle;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__halt_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__exc_ack;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__exc_kill;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_addr_rc_id;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_alu_waddr_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_alu_we_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_en;
        CData/*6:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_operator;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_op_a_mux_sel;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_op_b_mux_sel;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_op_c_mux_sel;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regc_mux;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_a_mux_sel;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_b_mux_sel;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__jump_target_mux_sel;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_operator;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_int_en;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_sel_subword;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_signed_mode;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_dot_en;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_dot_signed;
        IData/*17:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_read_regs;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_read_regs_valid;
        SData/*11:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_write_regs;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_write_regs_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_we_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_alu_waddr_mux_sel;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__data_we_id;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__data_type_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__data_sign_ext_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__data_req_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__data_load_event_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regid;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_we;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_we_int;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_target_mux_sel;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_start_mux_sel;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_cnt_mux_sel;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__csr_access;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__csr_status;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__prepost_useincr;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_a_fw_mux_sel;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_b_fw_mux_sel;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_c_fw_mux_sel;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__bmask_a_mux;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__bmask_b_mux;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_bmask_a_mux_sel;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_bmask_b_mux_sel;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_imm_mux;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__bmask_a_id_imm;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__bmask_b_id_imm;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_vec_mode;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__scalar_replication;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__reg_d_ex_is_reg_a_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__reg_d_ex_is_reg_b_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__reg_d_ex_is_reg_c_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__reg_d_wb_is_reg_a_id;
    };
    struct {
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__reg_d_alu_is_reg_a_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__regfile_mem_we;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__regfile_alu_we;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__data_req;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__hwloop_we;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__csr_illegal;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__jump_in_id;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__csr_op;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__ctrl_fsm_cs;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__ctrl_fsm_ns;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__jump_done;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__jump_done_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__jump_in_dec;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__branch_in_id;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__boot_done;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__boot_done_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__irq_enable_int;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__exc_ctrl_cs;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__exc_ctrl_ns;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__irq_id_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__irq_sec_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__regfile_we_lsu;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__regfile_waddr_lsu;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__fpu_busy;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__apu_req;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__apu_ready;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__apu_gnt;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__div_shift;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__div_valid;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_op_b_negate;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_left;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_use_round;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_arithmetic;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__is_equal;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__is_greater;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__f_is_greater;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__cmp_signed;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__is_equal_vec;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__is_greater_vec;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__cmp_result;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__f_is_nan;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__sel_minmax;
        CData/*7:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_byte_sel;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_reg_sel;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_reg1_sel;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_reg0_sel;
        CData/*3:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_through;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__cnt_result;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__bitop_result;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__div_ready;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_op_a_signed;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_popcnt_i__DOT__cnt_l1;
        IData/*23:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_popcnt_i__DOT__cnt_l2;
        SData/*15:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_popcnt_i__DOT__cnt_l3;
        SData/*9:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_popcnt_i__DOT__cnt_l4;
        WData/*159:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_ff_i__DOT__index_lut[5];
        WData/*159:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_ff_i__DOT__index_nodes[5];
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__RemSel_SN;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__RemSel_SP;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__CompInv_SN;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__CompInv_SP;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResInv_SN;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResInv_SP;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__Cnt_DP;
    };
    struct {
        CData/*5:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__Cnt_DN;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ARegEn_S;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__BRegEn_S;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResRegEn_S;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ABComp_S;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__LoadEn_S;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__State_SN;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__State_SP;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_subword;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_signed;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_shift_arith;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_imm;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_subword;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_signed;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_shift_arith;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_carry_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_active;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_save;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_clearcarry;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_ready;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_CS;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_NS;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_type_q;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__rdata_offset_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_sign_ext_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_we_q;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__wdata_offset;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__CS;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__NS;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__csr_we_int;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__frm_q;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__frm_n;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__fflags_q;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__fflags_n;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__fprec_q;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__fprec_n;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__mstatus_q;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__mstatus_n;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__mcause_q;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__mcause_n;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__ucause_q;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__ucause_n;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__priv_lvl_n;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__priv_lvl_q;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__priv_lvl_reg_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__id_valid_q;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCMR_n;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCMR_q;
        CData/*4:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__pccr_index;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__pccr_all_sel;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__is_pccr;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__is_pcer;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__is_pcmr;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__rdata_sel_q;
        CData/*2:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__rdata_sel_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__state_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__state_n;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__settings_q;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__settings_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_rreq_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_rreq_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_fp_sel_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_fp_sel_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__jump_req_q;
    };
    struct {
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__jump_req_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__csr_req_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__csr_req_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_wreq;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_fp_wr;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__stall_cs;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__stall_ns;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_resume;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_halt;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_cause_q;
        CData/*5:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_cause_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_ssth_q;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_ssth_n;
        CData/*0:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__ssth_clear;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__pc_tracking_fsm_cs;
        CData/*1:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__pc_tracking_fsm_ns;
        SData/*14:0*/ __PVT__riscv_core_i__DOT__apu_flags_ex;
        SData/*11:0*/ __PVT__riscv_core_i__DOT__csr_addr;
        QData/*35:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_char_op_a;
        QData/*35:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_char_op_b;
        SData/*11:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_in;
        SData/*11:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_inc;
        SData/*11:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_inc_q;
        SData/*11:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCER_n;
        SData/*11:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCER_q;
        SData/*14:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__addr_q;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__apu_master_result_i;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__instr_rdata_id;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__pc_id;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__pc_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__alu_operand_a_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__alu_operand_b_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__alu_operand_c_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__mult_operand_a_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__mult_operand_b_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__mult_operand_c_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__mult_dot_op_a_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__mult_dot_op_b_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__mult_dot_op_c_ex;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__regfile_alu_wdata_fw;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__csr_rdata;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__csr_wdata;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__lsu_rdata;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__epc;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_addr_n;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_rdata;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__exc_pc;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__hwlp_target;
        IData/*23:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__trap_base_addr;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__instr_decompressed;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__hwloop_controller_i__DOT__j;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__addr_q;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__addr_n;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__addr_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__addr_real_next;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__rdata_last_q;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__rdata;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__rdata_unaligned;
        WData/*127:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__L0_buffer[4];
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__addr_q;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__instr_addr_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_i_type;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_vu_type;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_b;
    };
    struct {
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__jump_target;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_data_ra_id;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_data_rc_id;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_target;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_start_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_cnt;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_cnt_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_a_fw_id;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_b_fw_id;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_c_fw_id;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_b;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_b_vec;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_operand_a;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_operand_b;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_operand_c;
        WData/*1023:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__mem[32];
        WData/*1023:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__mem_fp[32];
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__we_a_dec;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__we_b_dec;
        QData/*63:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__hwlp_start_q;
        QData/*63:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__hwlp_end_q;
        QData/*63:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__hwlp_counter_q;
        QData/*63:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__hwlp_counter_n;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__i;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__apu_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__operand_a_rev;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__operand_a_neg_rev;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__bmask;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_op_a;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_op_b;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_amt_left;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_amt;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_amt_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_op_a;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_right_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_left_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__result_minmax;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__minmax_b;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_r1;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_r0;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_r1_in;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_r0_in;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__pack_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__ff_input;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__bextins_result;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_ff_i__DOT__sel_nodes;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResReg_DP;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResReg_DN;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResReg_DP_rev;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__AReg_DP;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__AReg_DN;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__BReg_DP;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__BReg_DN;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__AddMux_D;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__AddTmp_D;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__OutMux_D;
        IData/*16:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_op_a;
        IData/*16:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_op_b;
        WData/*71:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_char_mul[3];
    };
    struct {
        QData/*33:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_short_op_a;
        QData/*33:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_short_op_b;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_addr_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__rdata_q;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_rdata_ext;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__csr_wdata_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__csr_rdata_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__mepc_q;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__mepc_n;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__uepc_q;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__uepc_n;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__exception_pc;
        IData/*23:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__mtvec_reg_q;
        IData/*23:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__utvec_n;
        IData/*23:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__utvec_q;
        WData/*383:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_q[12];
        WData/*383:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_n[12];
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__perf_rdata;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__cs_registers_i__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__wdata_q;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_rdata;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__ppc_int;
        IData/*31:0*/ __PVT__riscv_core_i__DOT__debug_unit_i__DOT__npc_int;
        QData/*35:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_in_a;
        QData/*35:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_in_b;
        QData/*36:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_result_expanded;
        QData/*33:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_mac;
        QData/*33:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_result;
        WData/*67:0*/ __PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_short_mul[3];
        IData/*31:0*/ __PVT__riscv_core_i__DOT__apu_master_operands_o[3];
        IData/*31:0*/ __PVT__riscv_core_i__DOT__apu_operands_ex[3];
        IData/*31:0*/ __PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_operands[3];
    };
    
    // LOCAL VARIABLES
    CData/*1:0*/ riscv_core_i__DOT__if_stage_i__DOT____Vcellinp__hwloop_controller_i__hwlp_dec_cnt_id_i;
    CData/*0:0*/ riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT____Vcellinp__L0_buffer_i__hwlp_i;
    CData/*0:0*/ riscv_core_i__DOT__id_stage_i__DOT____Vcellinp__registers_i__we_b_i;
    CData/*5:0*/ riscv_core_i__DOT__id_stage_i__DOT____Vcellinp__registers_i__waddr_b_i;
    CData/*0:0*/ riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound1;
    CData/*0:0*/ riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound8;
    CData/*5:0*/ __Vtableidx1;
    CData/*5:0*/ __Vtableidx3;
    CData/*5:0*/ __Vtableidx4;
    SData/*8:0*/ __Vtableidx2;
    WData/*127:0*/ riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT____Vcellout__L0_buffer_i__rdata_o[4];
    IData/*31:0*/ riscv_core_i__DOT__id_stage_i__DOT____Vcellinp__registers_i__wdata_b_i;
    IData/*31:0*/ riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound2;
    IData/*31:0*/ riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound3;
    IData/*31:0*/ riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound4;
    IData/*31:0*/ riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound5;
    IData/*31:0*/ riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound6;
    IData/*31:0*/ riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound7;
    IData/*31:0*/ riscv_core_i__DOT____Vcellout__id_stage_i__apu_operands_ex_o[3];
    IData/*31:0*/ riscv_core_i__DOT____Vcellout__ex_stage_i__apu_master_operands_o[3];
    IData/*31:0*/ riscv_core_i__DOT____Vcellinp__ex_stage_i__apu_operands_i[3];
    static CData/*0:0*/ __Vtable1___PVT__riscv_core_i__DOT__if_stage_i__DOT__offset_fsm_ns[64];
    static CData/*0:0*/ __Vtable1___PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_ready[64];
    static CData/*0:0*/ __Vtable1___PVT__riscv_core_i__DOT__if_stage_i__DOT__branch_req[64];
    static CData/*0:0*/ __Vtable1___PVT__riscv_core_i__DOT__if_stage_i__DOT__valid[64];
    static CData/*3:0*/ __Vtable2___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__cmp_signed[512];
    static CData/*1:0*/ __Vtable3___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__State_SN[64];
    static CData/*0:0*/ __Vtable3___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__div_ready[64];
    static CData/*0:0*/ __Vtable3___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__LoadEn_S[64];
    static CData/*0:0*/ __Vtable3___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ARegEn_S[64];
    static CData/*0:0*/ __Vtable3___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__BRegEn_S[64];
    static CData/*0:0*/ __Vtable3___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResRegEn_S[64];
    static CData/*1:0*/ __Vtable4___PVT__riscv_core_i__DOT__load_store_unit_i__DOT__NS[64];
    static CData/*0:0*/ __Vtable4___PVT__data_req[64];
    static CData/*0:0*/ __Vtable4___PVT__riscv_core_i__DOT__lsu_ready_ex[64];
    static CData/*0:0*/ __Vtable4___PVT__riscv_core_i__DOT__lsu_ready_wb[64];
    
    // INTERNAL VARIABLES
  private:
    Vtop__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vtop_top);  ///< Copying not allowed
  public:
    Vtop_top(const char* name = "TOP");
    ~Vtop_top();
    
    // INTERNAL METHODS
    void __Vconfigure(Vtop__Syms* symsp, bool first);
    static void _combo__TOP__top__3(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__top__6(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__top__8(Vtop__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _sequent__TOP__top__4(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__top__5(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__top__7(Vtop__Syms* __restrict vlSymsp);
    static void _settle__TOP__top__1(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__top__2(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void traceInit(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg(VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
